#!/bin/bash
chosen=$(printf "Lock\nLogout\nSuspend\nReboot\nShutdown" | rofi -dmenu -p "Power")

case "$chosen" in
    Lock) i3lock -c 1a1a2e ;;
    Logout) i3-msg exit ;;
    Suspend) systemctl suspend ;;
    Reboot) systemctl reboot ;;
    Shutdown) systemctl poweroff ;;
esac
